[bootstrap-resolver]
address = "8.8.8.8:853"
protocol = "dot"

[resolvers.homelab]
address = "10.1.2.2:53"
protocol = "udp"

# ----------------- Privacy Focused ------------------

[resolvers.joindns4-doh]
address = "https://unfiltered.joindns4.eu/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.uncensoreddns-doh]
address = "https://anycast.uncensoreddns.org/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.applied-privacy-doh]
address = "https://doh.applied-privacy.net/query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.libredns-doh]
address = "https://doh.libredns.gr/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }


# ----------------- Fallback (Cloudflare and Google) ------------------

# ---------- Cloudflare ----------

[resolvers.cloudflare-doh]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.cloudflare-dot-1]
address = "1.0.0.1:853"
protocol = "dot"

[resolvers.cloudflare-dot-2]
address = "1.1.1.1:853"
protocol = "dot"

# ---------- Google ----------

[resolvers.google-dot-1]
address = "8.8.8.8:853"
protocol = "dot"

[resolvers.google-dot-2]
address = "8.8.4.4:853"
protocol = "dot"

[groups.google]
resolvers = ["google-dot-1", "google-dot-2"]
type = "fail-rotate"

[groups.cloudflare]
resolvers = ["cloudflare-dot-1", "cloudflare-dot-2", "cloudflare-doh"]
type = "fail-rotate"

# ------------ Resolver Grouping ------------

[groups.fallback-resolvers]
resolvers = ["cloudflare", "google"]
type = "fastest"

[groups.main-resolvers]
resolvers = ["libredns-doh", "applied-privacy-doh", "uncensoreddns-doh", "joindns4-doh"]
type = "fastest"

# ----------------- Merge ------------------

[groups.default]
type   = "fail-rotate"
resolvers = ["main-resolvers", "fallback-resolvers"]

[groups.default-updated-ttl]
type = "ttl-modifier"
resolvers = ["default"]
ttl-min = 300
ttl-max = 86400
ttl-select = "average"


[routers.main-router]
routes = [
  { name = '(^|\.)casa\.ayoubedd\.me\.$', resolver="homelab" },
 { resolver="default-updated-ttl" }, # default route
]

[groups.main-cached]
type = "cache"
resolvers = ["main-router"]
backend = {type = "memory", size = 10000}
cache-answer-shuffle = "round-robin"
cache-flush-query = "fflush."

[groups.main-prefetch]
type = "prefetch"
resolvers = ["main-cached"]
prefetch-window = "15m"
prefetch-threshold = 3
prefetch-cache-size = 256
prefetch-max-items = 50


[listeners.local-udp-ipv4]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "main-prefetch"

[listeners.local-tcp-ipv4]
address = "127.0.0.1:53"
protocol = "tcp"
resolver = "main-prefetch"

[listeners.local-udp-ipv6]
address = "[::1]:53"
protocol = "udp"
resolver = "main-prefetch"

[listeners.local-tcp-ipv6]
address = "[::1]:53"
protocol = "tcp"
resolver = "main-prefetch"
