[bootstrap-resolver]
address = "8.8.8.8:853"
protocol = "dot"

[resolvers.homelab]
address = "10.1.2.2:53"
protocol = "udp"

# ----------------- Privacy Focused ------------------

[resolvers.joindns4-doh]
address = "https://unfiltered.joindns4.eu/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.uncensoreddns-doh]
address = "https://anycast.uncensoreddns.org/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.applied-privacy-doh]
address = "https://doh.applied-privacy.net/query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.libredns-doh]
address = "https://doh.libredns.gr/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

# ----------------- Fallback (Cloudflare and Google) ------------------

# ---------- Cloudflare ----------

[resolvers.cloudflare-doh]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
enable-0rtt = true
doh = { idle-timeout = 60 }

[resolvers.cloudflare-dot-1]
address = "1.0.0.1:853"
protocol = "dot"

[resolvers.cloudflare-dot-2]
address = "1.1.1.1:853"
protocol = "dot"

# ---------- Google ----------

[resolvers.google-dot-1]
address = "8.8.8.8:853"
protocol = "dot"

[resolvers.google-dot-2]
address = "8.8.4.4:853"
protocol = "dot"

[groups.google]
resolvers = ["google-dot-1", "google-dot-2"]
type = "fail-back"

[groups.cloudflare]
resolvers = ["cloudflare-dot-1", "cloudflare-dot-2", "cloudflare-doh"]
type = "fail-back"

# ------------ Resolver Grouping ------------

[groups.fallback-resolvers]
resolvers = ["cloudflare", "google"]
type = "fastest"

[groups.main-resolvers]
resolvers = [
  "libredns-doh",
  "applied-privacy-doh",
  "uncensoreddns-doh",
  "joindns4-doh"
]
type = "fastest"

# ----------------- Merge ------------------

[groups.default-resolvers]
type = "fail-back"
resolvers = ["main-resolvers", "fallback-resolvers"]
reset-after = 60

[groups.default-collapsed]
type = "response-collapse"
resolvers = ["default-resolvers"]

[groups.default-minimized]
type = "response-minimize"
resolvers = ["default-collapsed"]

[groups.default-updated-ttl]
type = "ttl-modifier"
resolvers = ["default-minimized"]
ttl-min = 300
ttl-max = 86400
ttl-select = "average"

[groups.response-blocklist]
type = "response-blocklist-ip"
resolvers = ["default-updated-ttl"]
blocklist-refresh = 86400
blocklist-source = [
  { source = "https://github.com/cbuijs/accomplist/raw/refs/heads/main/spamhaus/plain.black.ipcidr.list" },
  { source = "https://github.com/cbuijs/accomplist/raw/refs/heads/main/malicious-ip/plain.black.ipcidr.list" },
]

[groups.query-blocklist]
type = "blocklist-v2"
resolvers = ["response-blocklist"]
allow-failure = true
blocklist-refresh = 86400
blocklist-source = [
  { format = "domain", source = "https://github.com/cbuijs/accomplist/raw/refs/heads/main/typosquat/routedns.blocklist.top-n.domain.list" },
  { format = "domain", source = "https://github.com/cbuijs/accomplist/raw/refs/heads/main/anti-track/routedns.blocklist.top-n.domain.list" },
  { format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/malicious-dom/routedns.blocklist.top-n.domain.list" },
  { format = "domain", source = "https://github.com/cbuijs/accomplist/raw/refs/heads/main/google/routedns.blocklist.top-n.domain.list" },
  { format = "domain", source = "https://github.com/cbuijs/accomplist/raw/refs/heads/main/easylist/routedns.blocklist.top-n.domain.list" },
]
allowlist-format = "domain"
allowlist = [
  '.vercel.app.',
  '.netlify.app.',
]

[groups.cache]
type = "cache"
resolvers = ["router"]
backend = { type = "memory", size = 10000 }
cache-answer-shuffle = "round-robin"
cache-flush-query = "fflush."

[groups.prefetch]
type = "prefetch"
resolvers = ["cache"]
prefetch-window = "15m"
prefetch-threshold = 3
# prefetch-cache-size = 1024
prefetch-max-items = 1024

[routers.router]
routes = [
  { name = '(^|\.)casa\.ayoubedd\.me\.$', resolver = "homelab" },
  { resolver = "query-blocklist" },  # default route
]

[listeners.local-udp-ipv4]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "prefetch"

[listeners.local-tcp-ipv4]
address = "127.0.0.1:53"
protocol = "tcp"
resolver = "prefetch"

[listeners.local-udp-ipv6]
address = "[::1]:53"
protocol = "udp"
resolver = "prefetch"

[listeners.local-tcp-ipv6]
address = "[::1]:53"
protocol = "tcp"
resolver = "prefetch"
